// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("grpccheck")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/grpccheckreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
