// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for grpccheck metrics.
type MetricsConfig struct {
	GrpccheckDuration         MetricConfig `mapstructure:"grpccheck.duration"`
	GrpccheckError            MetricConfig `mapstructure:"grpccheck.error"`
	GrpccheckResponseSize     MetricConfig `mapstructure:"grpccheck.response.size"`
	GrpccheckStatus           MetricConfig `mapstructure:"grpccheck.status"`
	GrpccheckTLSCertRemaining MetricConfig `mapstructure:"grpccheck.tls.cert_remaining"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		GrpccheckDuration: MetricConfig{
			Enabled: true,
		},
		GrpccheckError: MetricConfig{
			Enabled: true,
		},
		GrpccheckResponseSize: MetricConfig{
			Enabled: false,
		},
		GrpccheckStatus: MetricConfig{
			Enabled: true,
		},
		GrpccheckTLSCertRemaining: MetricConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for grpccheck metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
