// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	GrpccheckDuration: metricInfo{
		Name: "grpccheck.duration",
	},
	GrpccheckError: metricInfo{
		Name: "grpccheck.error",
	},
	GrpccheckResponseSize: metricInfo{
		Name: "grpccheck.response.size",
	},
	GrpccheckStatus: metricInfo{
		Name: "grpccheck.status",
	},
	GrpccheckTLSCertRemaining: metricInfo{
		Name: "grpccheck.tls.cert_remaining",
	},
}

type metricsInfo struct {
	GrpccheckDuration         metricInfo
	GrpccheckError            metricInfo
	GrpccheckResponseSize     metricInfo
	GrpccheckStatus           metricInfo
	GrpccheckTLSCertRemaining metricInfo
}

type metricInfo struct {
	Name string
}

type metricGrpccheckDuration struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills grpccheck.duration metric with initial data.
func (m *metricGrpccheckDuration) init() {
	m.data.SetName("grpccheck.duration")
	m.data.SetDescription("Measures the duration of the gRPC health check.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricGrpccheckDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("grpc.endpoint", grpcEndpointAttributeValue)
	dp.Attributes().PutStr("grpc.service", grpcServiceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricGrpccheckDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricGrpccheckDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricGrpccheckDuration(cfg MetricConfig) metricGrpccheckDuration {
	m := metricGrpccheckDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricGrpccheckError struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills grpccheck.error metric with initial data.
func (m *metricGrpccheckError) init() {
	m.data.SetName("grpccheck.error")
	m.data.SetDescription("Records errors occurring during gRPC health check.")
	m.data.SetUnit("{error}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricGrpccheckError) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string, errorMessageAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("grpc.endpoint", grpcEndpointAttributeValue)
	dp.Attributes().PutStr("grpc.service", grpcServiceAttributeValue)
	dp.Attributes().PutStr("error.message", errorMessageAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricGrpccheckError) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricGrpccheckError) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricGrpccheckError(cfg MetricConfig) metricGrpccheckError {
	m := metricGrpccheckError{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricGrpccheckResponseSize struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills grpccheck.response.size metric with initial data.
func (m *metricGrpccheckResponseSize) init() {
	m.data.SetName("grpccheck.response.size")
	m.data.SetDescription("Size of health check response in bytes.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricGrpccheckResponseSize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("grpc.endpoint", grpcEndpointAttributeValue)
	dp.Attributes().PutStr("grpc.service", grpcServiceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricGrpccheckResponseSize) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricGrpccheckResponseSize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricGrpccheckResponseSize(cfg MetricConfig) metricGrpccheckResponseSize {
	m := metricGrpccheckResponseSize{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricGrpccheckStatus struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills grpccheck.status metric with initial data.
func (m *metricGrpccheckStatus) init() {
	m.data.SetName("grpccheck.status")
	m.data.SetDescription("1 if the gRPC health check resulted in a SERVING status, otherwise 0.")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricGrpccheckStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("grpc.endpoint", grpcEndpointAttributeValue)
	dp.Attributes().PutStr("grpc.service", grpcServiceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricGrpccheckStatus) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricGrpccheckStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricGrpccheckStatus(cfg MetricConfig) metricGrpccheckStatus {
	m := metricGrpccheckStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricGrpccheckTLSCertRemaining struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills grpccheck.tls.cert_remaining metric with initial data.
func (m *metricGrpccheckTLSCertRemaining) init() {
	m.data.SetName("grpccheck.tls.cert_remaining")
	m.data.SetDescription("Time in seconds until certificate expiry, as specified by `NotAfter` field in the x.509 certificate. Negative values represent time in seconds since expiration.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricGrpccheckTLSCertRemaining) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcTLSIssuerAttributeValue string, grpcTLSCnAttributeValue string, grpcTLSSanAttributeValue []any) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("grpc.endpoint", grpcEndpointAttributeValue)
	dp.Attributes().PutStr("grpc.tls.issuer", grpcTLSIssuerAttributeValue)
	dp.Attributes().PutStr("grpc.tls.cn", grpcTLSCnAttributeValue)
	dp.Attributes().PutEmptySlice("grpc.tls.san").FromRaw(grpcTLSSanAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricGrpccheckTLSCertRemaining) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricGrpccheckTLSCertRemaining) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricGrpccheckTLSCertRemaining(cfg MetricConfig) metricGrpccheckTLSCertRemaining {
	m := metricGrpccheckTLSCertRemaining{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                          MetricsBuilderConfig // config of the metrics builder.
	startTime                       pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                 int                  // maximum observed number of metrics per resource.
	metricsBuffer                   pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                       component.BuildInfo  // contains version information.
	metricGrpccheckDuration         metricGrpccheckDuration
	metricGrpccheckError            metricGrpccheckError
	metricGrpccheckResponseSize     metricGrpccheckResponseSize
	metricGrpccheckStatus           metricGrpccheckStatus
	metricGrpccheckTLSCertRemaining metricGrpccheckTLSCertRemaining
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                          mbc,
		startTime:                       pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                   pmetric.NewMetrics(),
		buildInfo:                       settings.BuildInfo,
		metricGrpccheckDuration:         newMetricGrpccheckDuration(mbc.Metrics.GrpccheckDuration),
		metricGrpccheckError:            newMetricGrpccheckError(mbc.Metrics.GrpccheckError),
		metricGrpccheckResponseSize:     newMetricGrpccheckResponseSize(mbc.Metrics.GrpccheckResponseSize),
		metricGrpccheckStatus:           newMetricGrpccheckStatus(mbc.Metrics.GrpccheckStatus),
		metricGrpccheckTLSCertRemaining: newMetricGrpccheckTLSCertRemaining(mbc.Metrics.GrpccheckTLSCertRemaining),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricGrpccheckDuration.emit(ils.Metrics())
	mb.metricGrpccheckError.emit(ils.Metrics())
	mb.metricGrpccheckResponseSize.emit(ils.Metrics())
	mb.metricGrpccheckStatus.emit(ils.Metrics())
	mb.metricGrpccheckTLSCertRemaining.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordGrpccheckDurationDataPoint adds a data point to grpccheck.duration metric.
func (mb *MetricsBuilder) RecordGrpccheckDurationDataPoint(ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string) {
	mb.metricGrpccheckDuration.recordDataPoint(mb.startTime, ts, val, grpcEndpointAttributeValue, grpcServiceAttributeValue)
}

// RecordGrpccheckErrorDataPoint adds a data point to grpccheck.error metric.
func (mb *MetricsBuilder) RecordGrpccheckErrorDataPoint(ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string, errorMessageAttributeValue string) {
	mb.metricGrpccheckError.recordDataPoint(mb.startTime, ts, val, grpcEndpointAttributeValue, grpcServiceAttributeValue, errorMessageAttributeValue)
}

// RecordGrpccheckResponseSizeDataPoint adds a data point to grpccheck.response.size metric.
func (mb *MetricsBuilder) RecordGrpccheckResponseSizeDataPoint(ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string) {
	mb.metricGrpccheckResponseSize.recordDataPoint(mb.startTime, ts, val, grpcEndpointAttributeValue, grpcServiceAttributeValue)
}

// RecordGrpccheckStatusDataPoint adds a data point to grpccheck.status metric.
func (mb *MetricsBuilder) RecordGrpccheckStatusDataPoint(ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcServiceAttributeValue string) {
	mb.metricGrpccheckStatus.recordDataPoint(mb.startTime, ts, val, grpcEndpointAttributeValue, grpcServiceAttributeValue)
}

// RecordGrpccheckTLSCertRemainingDataPoint adds a data point to grpccheck.tls.cert_remaining metric.
func (mb *MetricsBuilder) RecordGrpccheckTLSCertRemainingDataPoint(ts pcommon.Timestamp, val int64, grpcEndpointAttributeValue string, grpcTLSIssuerAttributeValue string, grpcTLSCnAttributeValue string, grpcTLSSanAttributeValue []any) {
	mb.metricGrpccheckTLSCertRemaining.recordDataPoint(mb.startTime, ts, val, grpcEndpointAttributeValue, grpcTLSIssuerAttributeValue, grpcTLSCnAttributeValue, grpcTLSSanAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
